services:
    elastic:
        build:
            context: ./elastic
            dockerfile: Dockerfile
        ports:
            - "7520:9200"
            - "7530:9300"
        volumes:
            - "./elastic/data:/usr/share/elasticsearch/data"
        container_name: "elastic_ci"
        restart: always
    kibana:
        build:
            context: ./kibana
            dockerfile: Dockerfile
        ports:
            - "7540:5601"
        volumes:
            - "./kibana/data:/usr/share/kibana/config"
        container_name: "kibana_ci"
        restart: always
