services:
    elastic:
        build:
            context: ./elastic
            dockerfile: Dockerfile
        ports:
            - "7520:9200"
            - "7530:9300"
        volumes:
            - "./elastic/data:/usr/share/elasticsearch/data"
        container_name: "elastic_ci"
        restart: always
